name: innovator
description: Application for creating innovation

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  dio: ^4.0.6
  jiffy: ^5.0.0
  bubble: ^1.2.1
  chewie: ^1.3.2
  flutter_svg: any
  get_storage: ^2.0.3
  reorderables: ^0.4.4
  firebase_auth: ^3.3.15
  video_player: ^2.4.0
  url_launcher: ^6.1.0
  auto_size_text: ^3.0.0
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5
  firebase_core: ^1.15.0
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf